name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan Latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          coverage: none

      - name: Install dependencies
        env:
          XDEBUG_MODE: off
        run: |
          composer require \
            "laravel/framework:12.*" \
            "orchestra/testbench:10.*" \
            "filament/filament:5.*" \
            "livewire/livewire:^4.0" \
            "pestphp/pest:^4.0" \
            "pestphp/pest-plugin-laravel:^4.0" \
            "pestphp/pest-plugin-livewire:^4.0" \
            --no-interaction --no-update --no-progress --ansi
          composer update --prefer-stable --prefer-dist --no-interaction --no-progress --ansi

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
